#debug: true

server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: Spring Boot CRUD
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/best_bd?verifyServerCertificate=false&allowPublicKeyRetrieval=true&useSSL=false&requireSSL=false&useLegacyDatetimeCode=false&amp&serverTimezone=UTC
    username: root
    password: root
  jpa:
    #    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl:
          charset_name: UTF-8
          import_files: init-data.sql
    open-in-view: false
  devtools:
    livereload:
      enabled: true
    add-properties: true
  mvc:
    view:
      prefix: /templates/
      suffix: .html
    hidden-method:
      filter:
        enabled: true
  web:
    locale: ru_RU


logging:
  charset:
    console: UTF-8
#  level: info